### PR TITLE
Multiple displays using threads

### PR DESCRIPTION
**Pull request by sgjava**
@olikraus, so this code finally demonstrates multiple software I2C displays running concurrently. This is what I have been shooting for. arm-linux port is thread safe finally.

### CODE REVIEW

**Comment by sgjava** [comment]
IMG_20211118_133140

Still image of example program.

**Comment by olikraus** [comment]
Nice picture :-)

**Comment by sgjava** [comment]
@olikraus here's the youtube video https://www.youtube.com/watch?v=3IENDb5GNok. Will be cool once you merge.

**Comment by sgjava** [comment]
I was thinking about this and maybe dynamic buffer should be internalized in init_user_data in the port. Then the program doesn't have to worry about setting up buffer. Let me think about this a bit. I'll close this for now.

**Comment by olikraus** [comment]
Nice video :-)

**Pull request closed without merging**
