### PR TITLE
Add mui_Return to switch to parent window

### PR DESCRIPTION
**Pull request by qianfan-Zhao**

### CODE REVIEW

**Comment by olikraus** [comment]
I don't see the need for this. It could be implemented in the app event loop itself by checking for the key and forcefully jumping to the parent page.

**Comment by qianfan-Zhao** [comment]
Hi @olikraus, new version had pushed, please review again.

**Comment by olikraus** [comment]
https://github.com/olikraus/u8g2/issues/2468

**Comment by olikraus** [comment]
Currently I am working on a more complete solution for this, so I will not merge the PR.
The new solution will introduce a new back MUIF, which will allow to jump back to a previous form.

**Pull request closed without merging**
