### PR TITLE
[fix][arm-linux] Add fclose after writing

### PR DESCRIPTION
**Pull request by wuhanstudio**
This PR fixes https://github.com/olikraus/u8g2/issues/1638

### CODE REVIEW

**Comment by wuhanstudio** [comment]
Hi, @sgjava

Could you confirm this fixes your issue?

IMG_20211030_192704

**Comment by sgjava** [comment]
@wuhanstudio  I will test later today and report back.

**Comment by sgjava** [comment]
Just tested I2C and SPI at the same time. Looks like SPI issue resolved
IMG_20211030_174642
.

**Comment by wuhanstudio** [comment]
> @wuhanstudio Just tested I2C and SPI at the same time. Looks like SPI issue resolved. Thanks for fixing this, now I can test Java wrapper! IMG_20211030_174642 .

Cheers

**Pull request merged**
