### PR TITLE
Added Multiple SPI Display FAQ

### PR DESCRIPTION
**Pull request by neilpanchal**
Add FAQ item for multiple SPI displays

### CODE REVIEW

**Comment by olikraus** [comment]
Thanks!

**Comment by akamustang** [comment]
I was reading the FAQ and noticed both displays have `/*RS*/ 4` which had me confused as it contradicts the statement that separate RST lines are required.

Also I think it's worth mentioning the ability to do a global reset on a single pin via the `U8X8_PIN_NONE` method, although a bit hacky it seems like good information to have in the FAQ.

**Comment by akamustang** [comment]
Wow, crazy fast response, thanks for replying, it reads much clearer now.

**Comment by olikraus** [comment]
Thanks

**Pull request merged**
