### PR TITLE
Small changes

### PR DESCRIPTION
**Pull request by sgjava**
Removed static global variables. Really no reason to keep them static. Also small change to readme pointing to this project instead of my fork. @wuhanstudio

### CODE REVIEW

**Comment by sgjava** [comment]
Just caught this @olikraus , sorry.

**Comment by wuhanstudio** [comment]
Hi, @sgjava

Perhaps it's better to keep them static so that they are only visible within this file, and this also make sure that no one changes these variables unintentionally elsethere.

**Comment by sgjava** [comment]
Well the thought process is to be able to change these, so they are not hard coded. Then the calling program can set them. Should you really have to change the source of U8g2 to set buses? I mean I have a lot of boards and some don't have the hard coded buses. @wuhanstudio

**Comment by wuhanstudio** [comment]
> Well the thought process is to be able to change these, so they are not hard coded. Then the calling program can set them. Should you really have to change the source of U8g2 to set buses? I mean I have a lot of boards and some don't have the hard coded buses. @wuhanstudio

Actually, I mean it's better to design a function to change it so that we know we're changing the bus for u8g2, but not the bus for other applications.

**Comment by sgjava** [comment]
@wuhanstudio I agree, but the issue is one bus to many devices (I2C addresses for instance). It look like there's a PR sitting out there at least for I2C https://github.com/olikraus/u8g2/pull/1255. The you can have several u8g2_t in use. Then you have to revisit u8x8_byte_arm_linux_hw_i2c as it is not thread safe using statics to persist across calls:
`	static uint8_t buffer[32];
	static uint8_t buf_idx;
`

**Comment by wuhanstudio** [comment]
Indeed, as for now we are unable to create mutiple u8g2 instances for different i2c buses.

Looks like this is an issue that has been pending for a long time. What do you think it's the best way to add support for mutiple i2c and spi buses? @olikraus

**Comment by sgjava** [comment]
@wuhanstudio Well, so phase one was to modernize drivers (GPIO, I2C and SPI) which is complete. The second phase was to create a struct to hold this device info and tie it to u8g2_t somehow, so the callbacks would know which one to operate on. We would just need to move all the state into this struct and make the callbacks stateless (maybe only have a global array with these structs in u8g2port). So the thought process is figure out something unique inside u8g2_t to key off of. I'm not sure why @olikraus didn't merge https://github.com/olikraus/u8g2/pull/1255 other than not to pollute the structs with this info.

**Comment by olikraus** [comment]
I probably missed #1255 
But adding #ifdef UNIX would be good.

**Comment by olikraus** [comment]
Can you give me a summary which PRs are required? I didn't follow your discussion and i also away from my desktop PC. (Typing this from my smartphone)

**Comment by sgjava** [comment]
@olikraus ii would be very helpful if you added an ID var (uchar or whatever) to u8x8_struct with a getter and setter. Then you can track displays by ID and we can handle I2C, SPI, etc. info outside of those structures. https://github.com/olikraus/u8g2/pull/1255 is only for I2C, but we really need a way to handle anything in the various ports. Having a unique ID for each display will allow other structures to manage the state. I'm open to @wuhanstudio or anyone else's input.

Hopefully that makes sense. On Linux based SoCs you can have multiple displays and memory is not as much of a concern.

**Comment by olikraus** [comment]
As I mentioned, my access to GitHub is very limited at the moment (only smartphone).

**Comment by sgjava** [comment]
@olikraus I can do it later tonight and submit a PR with just that simple change. The work on the arm-linux one which will be more complex.

**Pull request closed without merging**
