### PR TITLE
DataGP1247AI datasheet

### PR DESCRIPTION
**Pull request by Zealota74**
Do you have and could you provide a datasheet for Futaba GP1247A or GP1287?

### CODE REVIEW

**Comment by izilzty** [comment]
I uploaded it here https://github.com/olikraus/u8g2/pull/1831#issuecomment-1089523019
It's an old component, so doesn't have the exact same datasheet, but GP1219 and GP1247&1287 are basically the same except for size and initialization parameters.
The initialization parameters in the code are what I found from the original device, it should be correct.

**Comment by Zealota74** [comment]
This datasheet I have already downloaded from futaba.com.jp
On this site there is more similar devices.  GP1229AI looks promises. It is vectored pdf not only image
Thanks anyway. 
[GP1229AI_B_03.pdf](https://github.com/olikraus/u8g2/files/9035479/GP1229AI_B_03.pdf)
image

**Comment by olikraus** [comment]
It would be really good to have the pull request content in English...

**Comment by izilzty** [comment]
Sorry about that, I have changed the comments in the code to English.

**Comment by izilzty** [comment]
I have deleted files that are not part of U8g2 and also tested the code again. I think it's ready to merge. :relaxed:

**Comment by olikraus** [comment]
Thanks for the cleanup. It looks much better now. :-)

**Comment by russ627** [comment]
[GP1287BI_SPEC_V.3.pdf](https://github.com/olikraus/u8g2/files/9126043/GP1287BI_SPEC_V.3.pdf)

Here is a GP1287 datasheet, could you help me get your code running on an arduino or Pi pico, I am not really a programmer and can get the standard libraries and tweak them but I am having difficulty getting your code to be added to my auduino U8G2library. Thanks in advance!

**Comment by izilzty** [comment]
This is the arduino library I created from commit 9c0dc04, it can be installed just like a normal library.
[u8g2_arduino_2.33.8.zip](https://github.com/olikraus/u8g2/files/9126401/u8g2_arduino_2.33.8.zip)
You need to remove the existing library and install this version. After the official release supports this display, you can delete this library and continue to use the official version. Hope it will help you.

**Comment by russ627** [comment]
It did, thanks!

**Pull request merged**
