### PR TITLE
Add support for GP1287AI and GP1247AI VFD

### PR DESCRIPTION
**Pull request by izilzty**
Hi, I added support for GP1287AI GP1247AI VFDs and tested 1 page buffer and 2 page buffer on Arduino 328P and full buffer on STM32.
If there is no problem, I hope it can be merged with the upstream.
I noticed that some files may be auto-generated, but I'm not sure how to modify them, if you can handle it would be greatly appreciated.

sorry for bad english

gp1287ai_u8g2_logo

### CODE REVIEW

**Comment by olikraus** [comment]
Thanks for your effort. What I do not understand: Why is there a need to change u8g2_ll_hvline.c 
There should be a solution without this modification.
Is the datasheet available?
Is there a way for me to buy this display?

**Comment by izilzty** [comment]
Thanks for reply.

Just like the Sharp ls013b7dh03, this series of VFDs requires the SPI of LSBFIRST. So I swapped the byte order of the command using SWAP8. 
But unlike ls013b7dh03, this series of VFD hardware is drawn from top to bottom, the existing ``u8g2_ll_hvline_vertical_top_lsb`` draws in the correct direction but in reverse byte order. I need to modify the byte order when drawing.

The data sheet for this series of VFDs has been attached. This datasheet is basically the same as the GP1287AI GP1247AI except for the resolution.
[GP1219AI_D_03.pdf](https://github.com/olikraus/u8g2/files/8422390/GP1219AI_D_03.pdf)

Both VFDs are custom made and disassembled from other equipment. I think they may not be readily available outside of China. But they have lower prices and more stock, so I would like to have code to drive them.
I can help you with any tests if needed.

**Comment by olikraus** [comment]
> I need to modify the byte order when drawing.

It would be much better to do this in the device function instead.

The question here is: Do we really need to spent time into this. You have a working copy of u8g2 for your project and the display is anyway not available in small quantities for DIY projects. So I would just keep everything as it is and those users who really got hands on your displays can use your lib.

**Comment by izilzty** [comment]
You are right. There may not be so many people using it. I will keep it in my library. Thank you for taking the time to deal with it.
I will close the pull requests

**Comment by olikraus** [comment]
🙂

**Pull request closed without merging**
