### PR TITLE
Use SPI block transfer on the ESP8266

### PR DESCRIPTION
**Pull request by dratini0**
On the benchmark, I think this it gave around 5 fps improvement on my ST7920 screen, but I didn't note down my results. I can re-do them, if necessary.

### CODE REVIEW

**Comment by olikraus** [comment]
No further response? Basically I can not merge because of the mentioned doubts.

**Comment by dratini0** [comment]
Sorry, what do you mean? What doubts do you have?

**Comment by olikraus** [comment]
The risk of breaking the releasefor the ESP8266  because of the 32 bit alignment are to high from my perspective, so i will reject this pull request.

**Comment by dratini0** [comment]
Uhh, I have discovered that it breaks as soon as I link it with GDBstub. I am not sure if it is related, but it is broken nonetheless. I will investigate. Thank you!

**Pull request closed without merging**
