### PR TITLE
Added spi_mode and max_speed to user data

### PR DESCRIPTION
**Pull request by sgjava**
All set @olikraus

### CODE REVIEW

**Comment by sgjava** [comment]
Thank you.

**Comment by shlyakpavel** [comment]
Why did you
1) Screw correct way of automatically setting SPI mode (replaced it to be always 0)
2) Screw c++ overloaded function (added another function instead). I think its was a correct cpp-way to do it

**Comment by sgjava** [comment]
You want it the old way using display version? What do you suggest?

**Comment by shlyakpavel** [comment]
> You want it the old way using display version? What do you suggest?

I want it to be old way unless advanced function is called. I just suggested it in my PR that was closed to merge yours

**Pull request merged**
