### PR TITLE
Added spi_mode and max_speed to user data

### PR DESCRIPTION
**Pull request by sgjava**
@shlyakpavel this should fix https://github.com/olikraus/u8g2/issues/1689 after @olikraus merges.

### CODE REVIEW

**Comment by shlyakpavel** [comment]
I think these args should be optional with default set to u8x8->display_info->spi_mode
There are many cased there's no need to care about mode and speed and the default values are just fine

**Comment by sgjava** [comment]
Then just write a wrapper function or submit a PR.

**Comment by sgjava** [comment]
Didn't mean to close PR @sgjava, thought it was issue on looking on phone.

**Comment by shlyakpavel** [comment]
Haha I've already opened another one https://github.com/olikraus/u8g2/pull/1695

**Comment by shlyakpavel** [comment]
You can cherry-pick [ec3380cf2e8ae779bd0908ce99de4b9ccd642a94](https://github.com/olikraus/u8g2/pull/1695/commits/ec3380cf2e8ae779bd0908ce99de4b9ccd642a94) here and I'll close mine

**Comment by sgjava** [comment]
I'll make changes in another PR.

**Pull request closed without merging**
