### PR TITLE
add rt-thread cpp examples

### PR DESCRIPTION
**Pull request by wuhanstudio**
Hi,

This PR adds ~50 examples for rt-thread.

All the examples can be selected from the msh command line prompt with auto-completion.

```
 \ | /
- RT -     Thread Operating System
 / | \     4.0.2 build Aug  7 2021
 2006 - 2019 Copyright by rt-thread team
msh >u8g2
u8g2_u8x8_16x16_font
u8g2_u8x8_flip_mode
u8g2_u8x8_graphic_test
u8g2_u8x8_hello_world
u8g2_u8x8_message_box
u8g2_u8x8_terminal
u8g2_page_buffer_chinese
u8g2_page_buffer_clip_window
u8g2_page_buffer_clock
u8g2_page_buffer_contrast_test
u8g2_page_buffer_devanagari
u8g2_page_buffer_direct_access
u8g2_page_buffer_draw_log
u8g2_page_buffer_ext_utf8
u8g2_page_buffer_fps
u8g2_page_buffer_flip_mode
u8g2_page_buffer_graphic_test
u8g2_page_buffer_hello_world
u8g2_page_buffer_icon_menu
u8g2_page_buffer_japanese
u8g2_page_buffer_korean
u8g2_page_buffer_power_save
u8g2_page_buffer_print_hello_world
u8g2_page_buffer_scrolling_text
u8g2_page_buffer_selection_list
u8g2_page_buffer_serial
u8g2_page_buffer_state_buffer_loop
u8g2_page_buffer_terminal
u8g2_page_buffer_u8g2_logo
u8g2_page_buffer_update_partly
u8g2_page_buffer_weather
u8g2_page_buffer_xbm
u8g2_page_buffer_xor_test
u8g2_game_space_trash
u8g2_game_trex
u8g2_full_buffer_fps
u8g2_full_buffer_fontusage
u8g2_full_buffer_graphic_test
u8g2_full_buffer_hello_world
u8g2_full_buffer_icon_menu
u8g2_full_buffer_print_utf8
u8g2_full_buffer_selection_list
u8g2_full_buffer_u8g2_logo
u8g2_full_buffer_update_area
u8g2_full_buffer_weather
u8g2_ssd1306_12864_4wire_hw_spi_example
u8g2_ssd1306_12864_4wire_sw_spi_example
u8g2_ssd1306_12864_hw_i2c_example
u8g2_ssd1306_12864_sw_i2c_example
msh >
```

### CODE REVIEW

**Comment by wuhanstudio** [comment]
All the examples are available in RT-Thread Studio packages settings.

image

**Comment by wuhanstudio** [comment]
Hi, here are tutorials for u8g2 on RT-Thread ;)

The POSIX support and RTT package center make it really fun to add various packages for embedded systems.

https://packages.rt-thread.org/en/

**RT-Thread Studio (Windows)**:

https://www.rt-thread.io/studio.html

Will be added soon.

**RT-Thread ENV (Ubuntu)**:

[asciicast](https://asciinema.org/a/433949)

**Comment by olikraus** [comment]
ok... if this helps...

**Comment by wuhanstudio** [comment]
> ok... if this helps...

Many thanks. The u8g2 package in the RTT Package Center can now be pulled from this repo directly.

**Pull request merged**
