### PR TITLE
Added spi_mode and max_speed to user data

### LINKED ISSUE #1689: Linux hw SPI: Custom SPI mode for a display
I need to setup custom SPI mode for a display. I have st7920 controller and I need to use mode 0 instead of 3. What I do now is a dirty hack:
image
Is there a way to do it correctly?

### PR DESCRIPTION
**Pull request by shlyakpavel**
Fixes #1689
Based on https://github.com/olikraus/u8g2/pull/1692
Thanks @sgjava

### CODE REVIEW

**Review by sgjava — CHANGES_REQUESTED** [review]
Change "custom" to "advance" to match c-periphery please.

**Comment by shlyakpavel** [comment]
> Change "custom" to "advance" to match c-periphery please.

Fine. Wait a bit

**Comment by shlyakpavel** [comment]
Again
Should I replace `init_spi_hw_custom_mode` with `init_spi_hw_advance_mode` or `init_spi_hw_advanced_mode` or `init_spi_hw_advance` or `init_spi_hw_advanced` ?
I'm not familiar with "c-periphery"

**Comment by sgjava** [comment]
I'm adding new PR.

**Comment by sgjava** [comment]
https://github.com/olikraus/u8g2/pull/1696

**Comment by sgjava** [comment]
@shlyakpavel changed to past tense https://github.com/olikraus/u8g2/pull/1697

**Comment by sgjava** [comment]
Try that out.

**Pull request closed without merging**
