### PR TITLE
Small changes to SPI init defaults

### PR DESCRIPTION
**Pull request by sgjava**
Small changes, thanks.

### CODE REVIEW

**Comment by shlyakpavel** [comment]
See https://github.com/olikraus/u8g2/pull/1699 hahaha

**Comment by sgjava** [comment]
I did, but your naming was wrong. I'm trying to keep things logical. Have a look at c-periphery. I'm not trying to hack up arm-linux, I'm trying to improve it.

**Comment by shlyakpavel** [comment]
> I did, but your naming was wrong. 

Ok, ok. I'll close my PR

**Comment by olikraus** [comment]
So I assume i should merge this PR, right?

**Comment by olikraus** [comment]
I feel i need more strict advices :-p

**Comment by sgjava** [comment]
Yes, you are good, thanks. Multiple displays running in threads coming up soon :)

**Pull request merged**
