### PR TITLE
Add st7920 256x32 display support

### PR DESCRIPTION
**Pull request by shlyakpavel**
Hello. I have implemented st7920-based 256x32 dots screen support for my project. I hope it is fine and can be merged upstream.

### CODE REVIEW

**Comment by shlyakpavel** [comment]
I am not sure if I need to change codebuild.c to support this

**Comment by shlyakpavel** [comment]
Dear maintainers,
I'd really love to get some feedback if this is mergeable or not and if I can change it to make it mergeable in case it's not.
Have a nice day!

**Comment by olikraus** [comment]
Thanks for the pull request
Yes codebuild.c would be required. In fact many other files are automatically generated from codebuild.c (like u8x8_d_setup.c and u8g2.h, but also the wiki pages)
What I actually miss in the pull request is the update for u8x8.h (the new device should be added there)

I could go ahead and add the missing files, just let me know.

**Comment by shlyakpavel** [comment]
@olikraus, I would really appreciated if you added these

**Comment by olikraus** [comment]
I have created an issue for this: https://github.com/olikraus/u8g2/issues/1593

**Comment by shlyakpavel** [comment]
I think it's time to close the Pull Request.
Again, thanks a lot for your help! I'm currently enjoying the working display :)
Have a nice day!

**Pull request closed without merging**
