### PR TITLE
[rt-thread] beautify rt-thread port codes

### PR DESCRIPTION
**Pull request by mysterywolf**
Use RT-Thread Standard label Micro to replace RTT_U8G2;
Add some comments for sconscript;
Remove LOCAL_CCFLAGS .
@wuhanstudio please review.
@olikraus please review.

### CODE REVIEW

**Comment by wuhanstudio** [comment]
Hi, would you add a short description for this PR so that other developers know what it's used for.

**Comment by mysterywolf** [comment]
> Hi, would you add a short description for this PR so that other developers know what it's used for.

OK, Done.

**Comment by wuhanstudio** [comment]
Hi, mysterywolf,

Indeed, it's better to use `__RTTHREAD__`, which is introduced in `RTT v4.0.3`, and I've tested it out on both RTT latest and RTT v4.0.3. Thanks for your help.

**Comment by wuhanstudio** [comment]
Hi, @olikraus, 

Would you like to merge this PR? Did not expect PRs from other developers in the RT-Thread community come so fast.

I'm always willing to help review and test on hardware for future PRs related to RTT. 

Thank you olikraus and mysterywolf,
Han

**Comment by mysterywolf** [comment]
Thank you very much.

**Pull request merged**
